### ISSUE TITLE
what's the default user/pass?

### ISSUE THREAD

**Issue by simonmurdock** [NAStools/netdata#1]
Always have this issue with readyNAS apps... might be stupid but I don't see it anywhere.

**Comment by NAStools** [comment]
The magic is in [https.conf](https://github.com/NAStools/netdata/blob/master/debian/readynas/https.conf):
`Include "/etc/frontview/apache/Admin_Auth.conf"` allows the local ReadyNAS admin user, or any other member of the _admin_ group, to login.
`Require group nastools-netdata` allows any user that is a member of the _nastools-netdata_ group to login as well.
